### ISSUE TITLE
Useful function

### ISSUE THREAD

**Issue by vapniks** [tarsius/save-sexp#1]
Here is a function that might be useful for users of this library. It removes any objects such as buffers and window configs that can't be read in from a file.

``` elisp
(defun remove-unreadable (tree)
  "Remove unreadable objects from TREE.
Return value has the same structure as TREE but with all unreadable objects removed."
  (cl-subst nil 'anywinorbuffer tree
        :test (lambda (a b)
            (condition-case err
            (and (atom b)
                 (read (format "%S" b))
                 nil)
              (error t)))))
```

**Comment by tarsius** [comment]
I don't see how this could be useful and it doesn't seem to have anything to do with this library.

**Comment by vapniks** [comment]
I used it in `policy-switch` to remove buffer and window objects from config data before saving the data to file with `save-sexp-save-setq`, since those objects cannot be read back in (they can be reconstructed from other information in the data structure being saved). 
I think there may be occasions where other people would also need to do that, which is why I think it is relevant to this library.

**Comment by tarsius** [comment]
This goes beyond what I have intended this library to do, which is to write readable data to a file. First converting non-readable data into readable data is of course something that one might wish to do in combination with this library. But how that has to happen depends a lot on the caller.

Using buffers as example, because that's what you do, the generic input would be just a list of buffers, not some data structure which contains the buffers as well as other information which can be used to regenerate the buffers. That's specific to your package.

---

Actually I have only kept this package alive so long because I had some private code which still used it. I have now stopped using that code and have also retired this package, i.e. moved it to the Emacsattic.

Are you interested in maintaining this? As you can see by the number of this issue, there's not really much interest in it. It does it's job just fine, but it would be desirable if some minor issues concerning whitespace inserted around inserted forms would be addressed. Other than that, I don't think there's much to do.

If you become the maintainer, then it would of course be up to you whether you want to extend its scope by adding functions such as the one you are proposing. But I would still suggest that you think about this particular case some more before adding this function. Does this really belong more with `save-sexp` than with `policy-switch`? Is it really likely that another package would have the exact same need?

**Comment by vapniks** [comment]
I'm not really interested in becoming maintainer, I've got too much elisp on my hands as it is. 
After doing some more investigation I have discovered `pcache`, which is being actively maintained, and is used by a few other libraries so I think I might change the `policy-switch` code to use that instead.
